/**
 * core.js — Research Suite 核心算法 (Pure JS, Zero Dependencies)
 * All algorithms, extractors, calculators — 一体化
 */
'use strict';

// ════════════════════════ MATH UTILS ════════════════════════
function normalCDF(z){return 0.5*(1+erf(Math.abs(z)/Math.sqrt(2)));}
function erf(x){const a1=.254829592,a2=-.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429,p=.3275911;const sign=x<0?-1:1;x=Math.abs(x);const t=1/(1+p*x);const y=1-((((((a5*t+a4)*t)+a3)*t+a2)*t+a1)*t*Math.exp(-x*x));return sign*y;}
function gammaLn(x){const c=[76.18009172947146,-86.50532032941677,24.01409824083091,-1.231739572450155,.001208650973866179,-.000005395239384953];let y=x,tmp=x+5.5;tmp-=(x+.5)*Math.log(tmp);let ser=1.000000000190015;for(let j=0;j<6;j++)ser+=c[j]/++y;return -tmp+Math.log(2.5066282746310005*ser/x);}
function regBeta(z,a,b){if(z===0||z===1)return z;const bt=Math.exp(gammaLn(a+b)-gammaLn(a)-gammaLn(b)+a*Math.log(z)+b*Math.log(1-z));return z<(a+1)/(a+b+2)?bt*betaCF(z,a,b)/a:1-bt*betaCF(1-z,b,a)/b;}
function betaCF(z,a,b){const MAXIT=200,EPS=1e-10;let c=1,d=1-(a+b)*z/(a+1);if(Math.abs(d)<1e-30)d=1e-30;d=1/d;let h=d;for(let m=1;m<MAXIT;m++){const m2=2*m,aa=m*(b-m)*z/((a+m2-1)*(a+m2));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;h*=d*c;aa=-(a+m)*(a+b+m)*z/((a+m2)*(a+m2+1));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;const del=d*c;h*=del;if(Math.abs(del-1)<EPS)break;}return h;}
function chi2CDF(x,df){if(df<=0||x<0)return x>=0?1:0;if(df>100){const z=(Math.pow(x/df,1/3)-(1-2/(9*df)))/Math.sqrt(2/(9*df));return normalCDF(z);}return 1-regBeta(df/(df+x),df/2,.5);}

// ════════════════════════ PICO ════════════════════════
class PICOExtractor{extract(text){const t=text.toLowerCase();const find=(pats)=>{const o=[];for(const p of pats){const rx=new RegExp(p,'gi');let m;while((m=rx.exec(t))!==null)o.push((m[1]||m[0]).trim());}return[...new Set(o)].filter(x=>x.length>3).slice(0,5);};const pop=find([`population[s]?[:\\s]+([^\\.]+)`]);const int_=find([`treated with ([\\w\\s]{3,30})`,`administration of ([\\w\\s]{3,30})`]);const comp=find([`compar(?:ed|ison)[:\\s]+([^\\.]+)`,`versus ([\\w\\s]{3,20})`]);const out=find([`outcome[s]?[:\\s]+([^\\.]+)`,`efficacy|safety|mortality|response rate`]);const st=[];if(/randomized|rct|randomised/.test(t))st.push('RCT');if(/cohort|prospective/.test(t))st.push('队列研究');return{population:pop,intervention:int_,comparison:comp,outcome:out,study_type:[...new Set(st)].slice(0,3),toMarkdown(){return`## PICO框架\n\n**P(人群)**: ${this.population.join(', ')||'待定义'}\n**I(干预)**: ${this.intervention.join(', ')||'待定义'}\n**C(对照)**: ${this.comparison.join(', ')||'待定义'}\n**O(结局)**: ${this.outcome.join(', ')||'待定义'}\n**研究类型**: ${this.study_type.join(', ')||'未指定'}`;}};}}

// ════════════════════════ RoB 2 ════════════════════════
class RoB2Assessor{assessText(text,title='Unknown'){const t=text.toLowerCase();const r={paper_title:title,randomization:/randomized|rct/.test(t)?'Low':(/quasi-random/.test(t)?'High':'Unknown'),allocation:/allocation concealment|sealed envelope/.test(t)?'Low':(/open-label/.test(t)?'High':'Unknown'),blinding_participants:/double-blind/.test(t)?'Low':(/open-label/.test(t)?'High':'Unknown'),blinding_outcome:/double-blind|independent/.test(t)?'Low':(/open-label/.test(t)?'High':'Unknown'),attrition:!/dropout|lost to follow/.test(t)?'Low':(/intention-to-treat|itt/.test(t)?'Low':'Some concerns'),reporting:/clinicaltrials\.gov|registration|protocol/.test(t)?'Low':'Some concerns',other:/funded by|conflict/.test(t)?'Some concerns':'Unknown',overall:'Unknown'};const concerns=['Some concerns','High'].filter(d=>['randomization','allocation','blinding_participants','blinding_outcome','attrition','reporting','other'].some(k=>r[k]===d)).length;r.overall=concerns===0?'Low':concerns<=2?'Some concerns':'High';r.toMarkdown=()=>{const e={Low:'✅','Some concerns':'⚠️',High:'❌',Unknown:'❓'};return`## RoB2质量评估: ${title}\n\n| 维度 | 判定 |\n|------|------|\n|D1 随机化|${e[r.randomization]} ${r.randomization}|\n|D2 分配隐蔽|${e[r.allocation]} ${r.allocation}|\n|D3 参与者盲法|${e[r.blinding_participants]} ${r.blinding_participants}|\n|D4 评估者盲法|${e[r.blinding_outcome]} ${r.blinding_outcome}|\n|D5 数据完整性|${e[r.attrition]} ${r.attrition}|\n|D6 选择性报告|${e[r.reporting]} ${r.reporting}|\n\n**综合判定: ${e[r.overall]} ${r.overall}**`;};return r;}}

// ════════════════════════ GRADE ════════════════════════
class GRADEAssessor{assess(outcome,studyDesign='RCT',kwargs={}){let score=studyDesign==='RCT'?4:2;for(const k of['risk_of_bias','inconsistency','indirectness','imprecision','publication_bias'])if(kwargs[k])score--;if(studyDesign!=='RCT')score+=['dose_response','large_magnitude','confounders'].filter(k=>kwargs[k]).length;score=Math.max(0,Math.min(5,score));const map={5:'High',4:'High',3:'Moderate',2:'Low',1:'Very Low',0:'Very Low'};const q=map[score]||'Unknown';const r={outcome,study_design:studyDesign,quality:q,...kwargs};r.toMarkdown=()=>`## GRADE: ${outcome}\n\n研究设计: ${studyDesign}\n证据质量: **${q}**\n降级: ${['risk_of_bias','inconsistency','indirectness','imprecision','publication_bias'].filter(k=>kwargs[k]).join(', ')||'无'}\n升级: ${['dose_response','large_magnitude','confounders'].filter(k=>kwargs[k]).join(', ')||'无'}`;return r;}}

// ════════════════════════ JBI ════════════════════════
class JBIAssessor{assess(text,studyType='RCT',title='Unknown'){const t=text.toLowerCase();const isRCT=/randomized|rct/.test(t);let score=0;if(isRCT){if(/randomized|randomised/.test(t))score++;if(/allocation concealment|sealed/.test(t))score++;if(/double-blind|blinded/.test(t))score++;if(/placebo|control/.test(t))score++;if(/outcomes? measured|validated/.test(t))score++;if(/intention-to-treat|multivariate/.test(t))score++;}const maxS=isRCT?10:8;const r={study_type:studyType,paper_title:title,score,max_score:maxS};r.qualityLabel=()=>(score/maxS>=.8?'✅ 高质量':score/maxS>=.5?'⚠️ 中等质量':'❌ 低质量');r.toMarkdown=()=>`${title}: ${score}/${maxS} — ${r.qualityLabel()}`;return r;}}

// ════════════════════════ EVIDENCE TABLE ════════════════════════
class EvidenceTableGenerator{generate(papers,format='markdown'){if(!papers||!papers.length)return'**无相关文献**';const rows=papers.map(p=>({name:`${(p.authors||['Unknown'])[0]} et al. (${p.year||'N/A'})`,year:p.year||'N/A',journal:p.journal||'N/A',source:p.source||'N/A',doi:p.doi||'N/R',citations:p.citations||0}));if(format==='csv')return['Study,Year,Journal,Source,DOI,Citations',...rows.map(r=>`"${r.name}",${r.year},"${r.journal}",${r.source},${r.doi},${r.citations}`)].join('\n');let md=`# 证据表格 (共${rows.length}项研究)\n\n| Study | Year | Journal | Source | DOI | Citations |\n|-------|------|---------|--------|-----|----------|\n`;md+=rows.map(r=>`| ${r.name} | ${r.year} | ${r.journal} | ${r.source} | ${r.doi} | ${r.citations} |`).join('\n');return md;}}

// ════════════════════════ PRISMA ════════════════════════
class PRISMAGenerator{generateManual(o={}){const d={dbRecords:o.dbRecords||0,duplicates:o.duplicates||0,afterDedup:0,query:o.query||'',databases:o.databases||[],date:new Date().toISOString().split('T')[0]};d.afterDedup=d.dbRecords-d.duplicates;d.screened=o.screened||d.afterDedup;d.excluded=o.excluded||0;d.assessed=o.assessed||0;d.includedReports=o.includedReports||0;return d;}toAsciiDiagram(d){return`\n╔══════════════════════════════════════════════════════════════════════╗
║  IDENTIFICATION                                    ║
╠══════════════════════════════════════════════════════════════════════╣
║  数据库检索 records=${String(d.dbRecords).padEnd(5)}  去重后=${String(d.afterDedup).padEnd(5)}              ║
╠══════════════════════════════════════════════════════════════════════╣
║  SCREENING                                         ║
╠══════════════════════════════════════════════════════════════════════╣
║  全文评估=${String(d.assessed).padEnd(5)}  排除=${String(d.excluded).padEnd(5)}                        ║
╠══════════════════════════════════════════════════════════════════════╣
║  INCLUDED                                          ║
╠══════════════════════════════════════════════════════════════════════╣
║  ✅ 纳入研究 =${String(d.includedReports).padEnd(5)}                                     ║
║  检索词: ${d.query.substring(0,48).padEnd(48)}     ║
╚══════════════════════════════════════════════════════════════════════╝`;}toJson(d){return JSON.stringify(d,null,2);}}

// ════════════════════════ IMRAD WRITER ════════════════════════
class IMRADWriter{generate(topic,papers=[],pico=null,sections=['background','methods','results','discussion']){const today=new Date().toISOString().split('T')[0];let o=`# ${topic}\n\n*自动生成综述草稿 · ${papers.length}篇文献 · ${today}*\n\n`;if(sections.includes('background')){o+=`## 1.引言(Introduction)\n\n###1.1研究背景\n\n${topic}是当前研究热点。本综述检索到${papers.length}篇文献，涵盖RCT、队列研究等。\n\n###1.2研究Gap\n\n1.现有研究样本量偏小\n2.长期随访数据不足\n3.亚组分析不一致\n\n###1.3研究目的\n\n系统评价${topic}的有效性和安全性。\n\n`;}if(sections.includes('methods')){o+=`## 2.方法(Methods)\n\n###2.1检索策略\n\n数据库：PubMed/arXiv/Semantic Scholar/OpenAlex\n检索词：${topic}\n检索日期：${today}\n\n###2.2纳入排除标准\n\n纳入：RCT、队列研究、病例对照\n排除：综述、病例报告、动物实验\n\n###2.3质量评估\n\nRoB2( RCT)/ROBINS-I(观察性)/GRADE\n\n`;}if(sections.includes('results')){o+=`## 3.结果(Results)\n\n共${papers.length}篇，纳入${Math.min(papers.length,10)}篇全文评估。\n\n`;papers.slice(0,10).forEach((p,i)=>{o+=`${i+1}. **${p.title||'N/A'}** — ${(p.authors||[]).join(', ')}(${p.year||'N/A'}) [${p.journal||'N/A'}]\n`;});o+='\n';}if(sections.includes('discussion')){o+=`## 4.讨论(Discussion)\n\n###4.1主要发现\n\n[待根据实际结果填写]\n\n###4.2局限性\n\n1.检索数据库有限\n2.方法学质量问题\n3.异质性较大\n\n###4.3结论\n\n[待填写]\n\n`;}if(papers.length>0){o+='## 参考文献\n\n';papers.slice(0,10).forEach((p,i)=>{const au=(p.authors||[]).join(', ');const doi=p.doi?` doi:${p.doi}`:'';o+=`${i+1}. ${au}(${p.year||'n.d.'}). ${p.title||'N/A'}. ${p.journal||'N/A'}${doi}.\n`;});}return o;}}

// ════════════════════════ REFERENCE FORMATTER ════════════════════════
class ReferenceFormatter{constructor(style='bibtex'){this.style=style;}format(papers){return papers.map(p=>{const authors=(p.authors||[]).join(' and ');const yr=p.year||'n.d.',title=p.title||'Untitled',journal=p.journal||'',doi=p.doi||'';if(this.style==='bibtex'){const k=((p.authors||['X'])[0].split(' ').pop()+yr).replace(/[^a-zA-Z0-9]/g,'');return`@article{${k},\n  title = {${title}},\n  author = {${authors}},\n  journal = {${journal}},\n  year = {${yr}},\n  doi = {${doi}},\n}`;}if(this.style==='ris'){let o='TY  - JOUR\n';(p.authors||[]).forEach(a=>o+=`AU  - ${a}\n`);return o+`TI  - ${title}\nJO  - ${journal}\nPY  - ${yr}\nDO  - ${doi}\nER  -\n`;}if(this.style==='vancouver'){const au=(p.authors||[]).length>6?(p.authors||[]).slice(0,3).map(a=>a.split(' ').pop()).join(', ')+', et al.':(p.authors||[]).map(a=>a.split(' ').pop()).join(', ');return`${au}. ${title}. ${journal}. ${yr}.${doi?` doi:${doi}`:''}.`;}if(this.style==='endnote'){let o='%0 Journal Article\n';(p.authors||[]).forEach(a=>o+=`%A ${a}\n`);return o+`%T ${title}\n%J ${journal}\n%D ${yr}\n%M ${doi}\nER  -\n`;}return'';}).join('\n');}}

// ════════════════════════ EFFECT SIZE EXTRACTOR ════════════════════════
class EffectSizeExtractor{extractAll(text){const results=[];const patterns=[{type:'RR',pat:/RR\s*=\s*([0-9.]+)/gi},{type:'OR',pat:/\bOR\s*=\s*([0-9.]+)/gi},{type:'HR',pat:/\bHR\s*=\s*([0-9.]+)/gi}];for(const {type,pat} of patterns){let m;while((m=pat.exec(text))!==null){const v=parseFloat(m[1]);if(!v||v<=0)continue;const ci=/95%\s*CI[:\s]+([0-9.]+)\s*[-–to]+\s*([0-9.]+)/i.exec(text.substring(m.index,m.index+200));const pv=/p\s*[=<>]\s*([0-9.]+)/.exec(text.substring(m.index-30,m.index+100));const cl=ci?parseFloat(ci[1]):null,cu=ci?parseFloat(ci[2]):null,pVal=pv?parseFloat(pv[1]):null;results.push({raw_text:m[0],type,point_estimate:v,ci_lower:cl,ci_upper:cu,p_value:pVal,significant:pVal!==null&&pVal<.05,ln_rr:type==='RR'||type==='OR'||type==='HR'?Math.log(v):v});}}return results;}}

// ════════════════════════ HETEROGENEITY CALCULATOR ════════════════════════
class HeterogeneityCalculator{calculate(effects){const n=effects.length;const lns=effects.map(e=>e.ln_rr||0);const vs=effects.map(e=>{if(e.ci_lower!==undefined&&e.ci_upper!==undefined&&e.ci_lower>0)return Math.pow((Math.log(e.ci_upper)-Math.log(e.ci_lower))/(2*1.96),2);return e.variance||(e.se?e.se*e.se:1);});const ws=vs.map(v=>1/Math.max(v,1e-6));const sumW=ws.reduce((a,b)=>a+b,0);const pooled=ws.reduce((s,w,i)=>s+w*lns[i],0)/sumW;const Q=ws.reduce((s,w,i)=>s+w*Math.pow(lns[i]-pooled,2),0);const df=n-1;const pV=1-chi2CDF(Q,df);const iSq=Q>0?Math.max(0,(Q-df)/Q*100):0;const hSq=df>0?Q/df:1;const tauSq=Q>df?Math.max(0,(Q-df)/(sumW-ws.reduce((s,w)=>s+w*w,0)/sumW)):0;const tau=Math.sqrt(tauSq);const i2Label=iSq<25?'低异质性':iSq<50?'中度异质性':iSq<75?'较高异质性':'高度异质性';const rec=pV<.1||iSq>50?'🔴建议随机效应模型':'🟢可用固定效应模型';const normW=ws.map(w=>w/sumW*100);return{n_studies:n,q_statistic:Q,df,p_value:pV,i_squared:iSq,h_squared:hSq,tau_squared:tauSq,tau,i2_label:i2Label,recommendation:rec,weights:normW,toMarkdown(){const e=iSq<25?'🟢':iSq<75?'🟡':'🔴';return`## 异质性分析\n\n|指标|数值|\n|--|--|\n|研究数|${n}|\n|Cochran Q|${Q.toFixed(3)}|\n|p值|${pV.toFixed(4)}|\n|**I²**|${e}**${iSq.toFixed(1)}%** ${i2Label}|\n|τ²|${tauSq.toFixed(4)}|\n\n**${rec}**`;};}}

// ════════════════════════ FOREST PLOT ════════════════════════
class ForestPlotGenerator{generate(studies,pooled,heterogeneity,model='random',effectType='RR'){const self={studies,pooled,heterogeneity,model,effect_type:effectType,summary_line:1.0};const fmt=(v)=>(effectType==='RR'||effectType==='OR'||effectType==='HR'?Math.exp(v):v).toFixed(2);self.toAscii=()=>{const nW=25;let o=`\n╔═══════════════════════════════════════════════════════════════════╗\n║  森林图 — ${effectType} (95%CI)                               ║\n╚═══════════════════════════════════════════════════════════════════╝\n\n${'研究'.padEnd(nW)}  ${'效应量'.padEnd(10)}  ${'95%CI'.padEnd(20)}  ${'权重'.padEnd(8)}\n${'─'.repeat(nW+44)}\n${'[汇总]'.padEnd(nW)}  ${fmt(pooled.effect).padEnd(10)}  ${fmt(pooled.ci_lower)}–${fmt(pooled.ci_upper).padEnd(17)}  ${'[100%]'.padEnd(8)}\n${'─'.repeat(nW+44)}\n`;for(const s of studies){const lnE=s.effect<-10?s.effect:Math.log(Math.max(s.effect,.001));const lnL=s.ci_lower>0?Math.log(s.ci_lower):s.ci_lower;const lnU=Math.log(Math.max(s.ci_upper,.001));o+=`${(s.name+' '+(s.year||'')).substring(0,nW).padEnd(nW)}  ${fmt(lnE).padEnd(10)}  ${fmt(lnL)}–${fmt(lnU).padEnd(17)}  ${s.weight.toFixed(1)}%\n`;}o+=`\n无效线:1.00 (${effectType})\n异质性:I²=${(heterogeneity.i2||0).toFixed(1)}% | Q=${(heterogeneity.q||0).toFixed(2)} | p=${(heterogeneity.p||'N/A').toString()}\n`;return o;};self.toJson=()=>JSON.stringify(self,null,2);self.toRevman=()=>{let o='<?xml version="1.0" encoding="UTF-8"?>\n<RevMan5Data>\n  <Analyses>\n    <Analysis id="1" name="Meta-analysis">\n      <EffectMeasure type="'+effectType+'"/>\n      <Model type="'+(model==='random'?'Random':'Fixed')+'"/>\n      <Data>\n';for(const s of studies){o+=`      <Study name="${s.name}" year="${s.year||''}"><Effect value="${Math.exp(s.effect).toFixed(3)}" ci_lower="${Math.exp(s.ci_lower).toFixed(3)}" ci_upper="${Math.exp(s.ci_upper).toFixed(3)}"/><Weight>${s.weight.toFixed(2)}</Weight></Study>\n`;}const pe=Math.exp(pooled.effect),pl=Math.exp(pooled.ci_lower),pu=Math.exp(pooled.ci_upper);o+=`      </Data>\n      <SummaryEffect value="${pe.toFixed(3)}" ci_lower="${pl.toFixed(3)}" ci_upper="${pu.toFixed(3)}" pvalue="${pooled.pvalue||0}"/>\n    </Analysis>\n  </Analyses>\n</RevMan5Data>\n`;return o;};self.toStata=()=>{let o='* Stata meta analysis input\ninput str50 study year effect selogci lower upper weight\n';for(const s of studies){const lnL=s.ci_lower>0?Math.log(s.ci_lower):s.ci_lower,lnU=Math.log(Math.max(s.ci_upper,.001));const se=(lnU-lnL)/(2*1.96);o+=`"${s.name}" ${s.year||0} ${Math.exp(s.effect).toFixed(4)} ${se.toFixed(4)} ${Math.exp(lnL).toFixed(4)} ${Math.exp(lnU).toFixed(4)} ${s.weight.toFixed(2)}\n`;}const pe=Math.exp(pooled.effect),pl=Math.exp(pooled.ci_lower),pu=Math.exp(pooled.ci_upper);o+=`"Summary" . ${pe.toFixed(4)} ${pl.toFixed(4)} ${pu.toFixed(4)} .\nend\n* Pooled: ${pe.toFixed(4)} (${pl.toFixed(4)}–${pu.toFixed(4)})\n`;return o;};return self;}}

// ════════════════════════ META ANALYZER ════════════════════════
class MetaAnalyzer{constructor(){this._s=[];}addStudyDirect(name,type,effect,ciL,ciU,year=null,nTotal=null,nEvents=null,group='',pVal=null){const lnE=type==='RR'||type==='OR'||type==='HR'?Math.log(Math.max(effect,.001)):effect;const lnL=ciL>0?Math.log(ciL):ciL,lnU=Math.log(Math.max(ciU,.001));const se=(lnU-lnL)/(2*1.96);this._s.push({name,year,type,raw:effect,ciL,ciU,nTotal,nEvents,group,pVal,lnE,lnL,lnU,var:se*se});}analyze(model=null){if(this._s.length<2)return{error:'需要至少2项研究'};const calc=new HeterogeneityCalculator();const effs=this._s.map(s=>({ln_rr:s.lnE,ci_lower:s.lnL,ci_upper:s.lnU}));const het=calc.calculate(effs);if(!model)model=het.p_value<.1||het.i_squared>50?'random':'fixed';const ws=this._s.map(s=>1/Math.max(s.var,1e-6));const sumW=ws.reduce((a,b)=>a+b,0);let lnP=ws.reduce((a,w,i)=>a+w*this._s[i].lnE,0)/sumW;if(model==='random'){const tSq=het.tau_squared;const adjW=this._s.map(s=>1/Math.max(s.var+tSq,1e-6));const sumWA=adjW.reduce((a,b)=>a+b,0);lnP=adjW.reduce((a,w,i)=>a+w*this._s[i].lnE,0)/sumWA;}const pV2=1/sumW,pSE=Math.sqrt(pV2),lnCL=lnP-1.96*pSE,lnCU=lnP+1.96*pSE;const z=lnP/pSE,pVal=2*(1-normalCDF(Math.abs(z)));const et=this._s[0]?.type||'RR';const toR=v=>et==='RR'||et==='OR'||et==='HR'?Math.exp(v):v;const nW=ws.map(w=>w/sumW*100);this._s.forEach((s,i)=>s.wPct=nW[i]);const pe=Math.exp(lnP),pl=Math.exp(lnCL),pu=Math.exp(lnCU);return{n_studies:this._s.length,model,effect_type:et,pooled:{effect:toR(lnP),ci_lower:toR(lnCL),ci_upper:toR(lnCU),pvalue:pVal,significant:pVal<.05},heterogeneity:{q:Number(het.q_statistic.toFixed(3)),df:het.df,p:Number(het.p_value.toFixed(4)),i2:Number(het.i_squared.toFixed(1)),tau2:Number(het.tau_squared.toFixed(4)),label:het.i2_label},recommendation:het.recommendation,studies:this._s.map(s=>({name:s.name,year:s.year,effect:Number((s.raw||0).toFixed(3)),ci:`[${Number((s.ciL||0).toFixed(3))}, ${Number((s.ciU||0).toFixed(3))}]`,weight:Number((s.wPct||0).toFixed(1)),p:s.pVal})),toReport(){let o=`╔══════════════════════════════════════════════════════════════╗\n║  🔬Meta分析结果报告                                  ║\n╚══════════════════════════════════════════════════════════════╝\n\n`;o+=`📊 ${this.n_studies}项研究 | ${this.model==='random'?'随机':'固定'}效应 | ${this.effect_type}\n\n`;o+=`📈 合并${this.effect_type}=${this.pooled.effect.toFixed(3)} (95%CI:${this.pooled.ci_lower.toFixed(3)}–${this.pooled.ci_upper.toFixed(3)}) p=${this.pooled.pvalue.toFixed(4)} — ${this.pooled.significant?'✅显著':'❌不显著'}\n\n`;o+=`📐 I²=${this.heterogeneity.i2}% Q=${this.heterogeneity.q} p=${this.heterogeneity.p} — ${this.heterogeneity.label}\n\n`;o+=`📋各研究:\n${'研究'.padEnd(25)}${'年份'.padEnd(6)}${this.effect_type.padEnd(8)}${'95%CI'.padEnd(20)}${'权重'.padEnd(8)}\n${'─'.repeat(67)}\n`;this.studies.forEach(s=>{o+=`${s.name.padEnd(25)}${String(s.year||'N/A').padEnd(6)}${s.effect.toFixed(3).padEnd(8)}${s.ci.padEnd(20)}${s.weight.toFixed(1)}%\n`;});return o;};}}

// ════════════════════════ ENTITY EXTRACTOR ════════════════════════
class EntityExtractor{extractEntities(text,pmid=''){const entities=[],seen=new Set();const dict={gene:['TP53','BRCA1','BRCA2','EGFR','KRAS','MYC','PTEN','HER2','PD-1','PD-L1','CTLA-4','VEGF','IL-6','TNF-α','IFN-γ','STAT3','AKT','mTOR','PI3K','MAPK','ERK','BRAF','BCL-2','CD8','CD4','Treg','NK','DC','Macrophage'],disease:['cancer','tumor','carcinoma','melanoma','lymphoma','leukemia','diabetes','obesity','hypertension','cardiovascular','stroke','Alzheimer','Parkinson','depression','arthritis','asthma','infection','sepsis','COVID','influenza'],drug:['aspirin','metformin','insulin','atorvastatin','paclitaxel','doxorubicin','cisplatin','trastuzumab','pembrolizumab','nivolumab','ipilimumab','dexamethasone','prednisone','cyclosporine','tacrolimus','rapamycin','imatinib','rituximab'],pathway:['PI3K/AKT','mTOR','MAPK','ERK','JAK/STAT','TGF-β','NF-κB','WNT','HIF','AMPK','Notch','Hedgehog','Apoptosis','Cell cycle','DNA repair','Angiogenesis','PD-1/PD-L1','CTLA-4'],symptom:['fatigue','pain','fever','inflammation','edema','rash','headache','nausea','vomiting','diarrhea','dyspnea','cough','anemia','weight loss','insomnia','anxiety']};for(const[type,terms]of Object.entries(dict)){for(const term of terms){if(new RegExp('\\b'+term.replace('-','\\-')+'\\b','i').test(text)){const id=`${type}:${term.replace(/\s+/g,'_').toUpperCase()}`;if(!seen.has(id)){seen.add(id);entities.push({id,name:term,type,source:pmid,properties:{}});}}}}return entities;}}

// ════════════════════════ RELATION EXTRACTOR ════════════════════════
class RelationExtractor{extractRelations(text,entities,pmid=''){const rels=[],seen=new Set();const em=Object.fromEntries(entities.map(e=>[e.name.toUpperCase(),e.id]));const pats={upregulates:[/(\w+)\s+(?:up[-]?regulated|increased|elevated|enhanced)\s+(?:in|by|through)?\s*(\w+)/gi],downregulates:[/(\w+)\s+(?:down[-]?regulated|decreased|reduced)\s+(?:in|by)?\s*(\w+)/gi,/(\w+)\s+(?:inhibits?|blocks?)\s+(\w+)/gi],treats:[/(\w+)\s+(?:treats?|ameliorates?|alleviates?)\s+(?:the\s+)?(\w+)/gi],causes:[/(\w+)\s+(?:causes?|induces?)\s+(\w